# Generated by Django 4.1.5 on 2023-01-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('hid', models.IntegerField(db_column='hID', primary_key=True, serialize=False)),
                ('networth', models.IntegerField(blank=True, db_column='netWorth', null=True)),
                ('childrennum', models.IntegerField(blank=True, db_column='ChildrenNum', null=True)),
            ],
            options={
                'db_table': 'Households',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('title', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Recordreturns',
            fields=[
                ('title', models.OneToOneField(db_column='title', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Media_App.programs')),
                ('hid', models.ForeignKey(db_column='hID', on_delete=django.db.models.deletion.DO_NOTHING, to='Media_App.households')),
            ],
            options={
                'db_table': 'RecordReturns',
                'unique_together': {('title', 'hid')},
            },
        ),
        migrations.CreateModel(
            name='Recordorders',
            fields=[
                ('title', models.OneToOneField(db_column='title', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Media_App.programs')),
                ('hid', models.ForeignKey(db_column='hID', on_delete=django.db.models.deletion.DO_NOTHING, to='Media_App.households')),
            ],
            options={
                'db_table': 'RecordOrders',
                'unique_together': {('title', 'hid')},
            },
        ),
        migrations.CreateModel(
            name='Programranks',
            fields=[
                ('title', models.OneToOneField(db_column='title', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Media_App.programs')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('hid', models.ForeignKey(db_column='hID', on_delete=django.db.models.deletion.DO_NOTHING, to='Media_App.households')),
            ],
            options={
                'db_table': 'ProgramRanks',
                'unique_together': {('title', 'hid')},
            },
        ),
    ]
